services:
  mysqldb:
    image: mysql:8.0.36-debian
    container_name: mysqldb
    ports:
      - 3306:3306
    volumes:
      - data:/data/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: automotive_storage
      MYSQL_PASSWORD: root
    networks:
      - springmysql

  transit-system:
    build: .
    # image: diegopimenta/transit-system-backend:latest
    container_name: transit-system
    ports:
      - 8081:8081
    environment:
      HOST: mysqldb
    depends_on:
      - mysqldb
    networks:
      - springmysql
    restart: on-failure

volumes:
  data:

networks:
  springmysql:
