spring:
  application:
    name: transit-system
  port: 8081
  servlet:
    context-path: /api

  # Database Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${HOST:localhost}:3306/automotive_storage?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root

  # JPA Properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  # Initialize SQL Script
  sql:
    init:
      mode: always
